### ISSUE TITLE
Only have the coded quests in the quest list.

### ISSUE THREAD

**Issue by AgilityV2** [dginovker/2006rebotted#25]
Right now we have a bunch of quests on the quest list that aren't coded, here's a list of coded quests:
https://github.com/dginovker/2006rebotted/tree/master/2006Redone%20Server/src/redone/game/content/quests/impl

**Comment by dginovker** [comment]
This code doesn't work, since q.getButton() isn't the ID you want.
![image](https://user-images.githubusercontent.com/32943174/66280409-8b2fbf00-e884-11e9-983e-2c8f881f6bf3.png)

The ID you want (seen highlighted here) isn't incremented by 1 as you go down the quest list, and I can't figure out a way to dump it.
![image](https://user-images.githubusercontent.com/32943174/66280388-76ebc200-e884-11e9-912b-cae4dffb480a.png)

However, if you can dump it, the code to make this work would look like:

```
for (Integer i : array_of_quest_interface_values)
{
    player.getPlayerAssistant().sendFrame126("@str@" + quest_name, i);
    //Or if you don't have the quest_name, just leave it as ""
}
```

**Comment by Dark98** [comment]
This was fixed by @mrextremez
